# Generated by Django 4.2.17 on 2024-12-06 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                ("creator_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_joined_as_creator", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True, max_length=1000, null=True)),
                ("social_links", models.JSONField(blank=True, default=dict, null=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "niche",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blogapp.category",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_creator", models.BooleanField(default=False)),
                ("sex", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profil_pic/"),
                ),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "bookmarked_post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="blogapp.post",
                    ),
                ),
                (
                    "followed_craetors",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="authapp.creatorprofile",
                    ),
                ),
                (
                    "like_post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_by",
                        to="blogapp.post",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
